#!/bin/bash

path="/sys/class/backlight/*/brightness"
echo $path

get_brightness () {
    old=$(cat $path)
}

set_brightness () {
    new=$1
    new=$(( $new>0 ? $new : 0 ))
    new=$(( $new<255 ? $new : 255 ))
    echo $new > $path
    echo brightness set to $new
}

inc_brightness () {
    get_brightness
    set_brightness $(( $old + $1 ))
}

write_access() {
    sleep 1
    chmod 666 $path
}


amt="${2:-16}"

case $1 in
    -init|init)
        write_access
        ;;
    -set|set)
        set_brightness $amt
        ;;
    -inc|inc)
        inc_brightness $amt
        ;;
    -dec|dec)
        inc_brightness -$amt
        ;;
    -get|get)
        get_brightness
        echo $old
        ;;
esac

